version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/opt/blog/
      - /opt/blog/node_modules
    ports:
      - "4567:4567"
  tailwind:
    build:
      context: .
      dockerfile: Dockerfile-tailwind.development
    volumes:
      - .:/opt/blog/
    tty: true
